### ISSUE TITLE
glpi-9.2 is not yet supported

### ISSUE THREAD

**Issue by yoshi314** [bacus99/Services#11]
Any eta on 9.2 update?

**Comment by yoshi314** [comment]
It seems to work more or less fine after manually updating the hook.php, though. I'll do some tests.


edit in new service entry form : 

```
Last disaster recovery tested | Fatal error:  Call to undefined method Html::showDateFormItem() in /usr/share/glpi/plugins/services/inc/service.class.php on line 587
```

**Comment by yoshi314** [comment]
Patches so far : 

```
diff --git a/inc/service.class.php b/inc/service.class.php
index ec5975b..a81ef4b 100644
--- a/inc/service.class.php
+++ b/inc/service.class.php
@@ -584,12 +584,18 @@ class PluginServicesService extends CommonDBTM {
          echo "<tr class='tab_bg_1'>";
       echo "<td>".__('Last disaster recovery tested')."</td>";
       echo "<td>";
-      Html::showDateFormItem("date_last_dr",$this->fields["date_last_dr"],true,true);
+      Html::showDateField("date_last_dr",[ 
+               'value'         => $this->fields["date_last_dr"],
+               'maybeempty'    => true,
+               'canedit'       => true]);
       echo "</td>";      
          
       echo "<td>".__('Next disaster recovery planning')."</td>";
       echo "<td>";
-      Html::showDateFormItem("date_next_dr",$this->fields["date_next_dr"],true,true);
+      Html::showDateField("date_next_dr", [
+               'value'         => $this->fields["date_next_dr"],
+               'maybeempty'    => true,
+               'canedit'       => true]);
       echo "</td>";      
           
          //  ---- End of 2 -----
@@ -869,4 +875,4 @@ class PluginServicesService extends CommonDBTM {
       parent::processMassiveActionsForOneItemtype($ma, $item, $ids);
    }
 }
-?>
\ No newline at end of file
+?>
diff --git a/setup.php b/setup.php
index 972379e..f0c1786 100644
--- a/setup.php
+++ b/setup.php
@@ -112,7 +112,7 @@ function plugin_version_services() {
 // Optional : check prerequisites before install : may print errors or add to message after redirect
 function plugin_services_check_prerequisites() {
 
-   if (version_compare(GLPI_VERSION,'9.1','lt') || version_compare(GLPI_VERSION,'9.2','ge')) {
+   if (version_compare(GLPI_VERSION,'9.1','lt') || version_compare(GLPI_VERSION,'9.3','ge')) {
       _e('This plugin requires GLPI >= 9.1', 'services');
       return false;
    }
```

If i get it working i'll setup a for with PR for improvements.

**Comment by bacus99** [comment]
Hi Marcin, i have a.new version compatible with 9.2 not ready tonshare yet.  i can send you tuesday to test?  Upgrade is not done yet so we need to uninstall and reinstall + restore tables

Sent from BlueMail<http://www.bluemail.me/r?b=12656>
On Mar 30, 2018, at 6:59 AM, Marcin Kowalski <notifications@github.com<mailto:notifications@github.com>> wrote:

Any eta on 9.2 update?

**Comment by yoshi314** [comment]
Sure, i can give it a test.

**Comment by Douille560** [comment]
Hi, any news on 9.2 glpi version supported ???

**Comment by bacus99** [comment]
Hi, I currently  have a version for 9.2.4.  Willing to test in dev?  Currently working but update cause me issues (I had to apply the SQL update script manually)

This is my PROD version which I updated lately, manually

![image](https://user-images.githubusercontent.com/11425241/41796604-3801abee-7635-11e8-82a9-e220699ba77f.png)

[services.zip](https://github.com/bacus99/Services/files/2128990/services.zip)

**Comment by Douille560** [comment]
Thx.

For a purpose test, do you have the version for 9.2 ?

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : vendredi, juin 22, 2018 15:57 PM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


Hi, I currently have a version for 9.2.4. Willing to test in dev? Currently working but update cause me issues (I had to apply the SQL update script manually)
services.zip<https://github.com/bacus99/Services/files/2128990/services.zip>

**Comment by bacus99** [comment]
You installed version 1.3.1 from the link below you thread?

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On Jun 26, 2018, at 8:11 AM, Douille560 <notifications@github.com<mailto:notifications@github.com>> wrote:
Thx.

For a purpose test, do you have the version for 9.2 ?

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : vendredi, juin 22, 2018 15:57 PM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


Hi, I currently have a version for 9.2.4. Willing to test in dev? Currently working but update cause me issues (I had to apply the SQL update script manually)
services.zip<https://github.com/bacus99/Services/files/2128990/services.zip>

**Comment by bacus99** [comment]
Should be compatible 9.2 too

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On Jun 26, 2018, at 8:11 AM, Douille560 <notifications@github.com<mailto:notifications@github.com>> wrote:
Thx.

For a purpose test, do you have the version for 9.2 ?

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : vendredi, juin 22, 2018 15:57 PM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


Hi, I currently have a version for 9.2.4. Willing to test in dev? Currently working but update cause me issues (I had to apply the SQL update script manually)
services.zip<https://github.com/bacus99/Services/files/2128990/services.zip>

**Comment by Douille560** [comment]
Yes,

But I’m looking to go in a prod version 9.2 of GPLI soon.  I’m not ready to go to 9.2.4 because of the others plugins we have installed.

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : mardi, juin 26, 2018 9:02 AM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)

You installed version 1.3.1 from the link below you thread?

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On Jun 26, 2018, at 8:11 AM, Douille560 <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>> wrote:
Thx.

For a purpose test, do you have the version for 9.2 ?

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com%3cmailto:sdoyon@canadianmalartic.com>> | www.canadianmalartic.com<http://www.canadianmalartic.com/<http://www.canadianmalartic.com%3chttp:/www.canadianmalartic.com/>>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com<mailto:notifications@github.com>>
Envoyé : vendredi, juin 22, 2018 15:57 PM
À : bacus99/Services <Services@noreply.github.com<mailto:Services@noreply.github.com>>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com>>; Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


Hi, I currently have a version for 9.2.4. Willing to test in dev? Currently working but update cause me issues (I had to apply the SQL update script manually)
services.zip<https://github.com/bacus99/Services/files/2128990/services.zip>

**Comment by Douille560** [comment]
[cid:image001.png@01D40D2C.D00D6D50]

It’s says not compatible !!!
THX
[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : mardi, juin 26, 2018 9:02 AM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)

Should be compatible 9.2 too

Sent from BlueMail<http://www.bluemail.me/r?b=13187>
On Jun 26, 2018, at 8:11 AM, Douille560 <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>> wrote:
Thx.

For a purpose test, do you have the version for 9.2 ?

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com%3cmailto:sdoyon@canadianmalartic.com>> | www.canadianmalartic.com<http://www.canadianmalartic.com/<http://www.canadianmalartic.com%3chttp:/www.canadianmalartic.com/>>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com<mailto:notifications@github.com>>
Envoyé : vendredi, juin 22, 2018 15:57 PM
À : bacus99/Services <Services@noreply.github.com<mailto:Services@noreply.github.com>>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com>>; Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


Hi, I currently have a version for 9.2.4. Willing to test in dev? Currently working but update cause me issues (I had to apply the SQL update script manually)
services.zip<https://github.com/bacus99/Services/files/2128990/services.zip>

**Comment by bacus99** [comment]
try this version
[services.zip](https://github.com/bacus99/Services/files/2137547/services.zip)

**Comment by Douille560** [comment]
Hi Christian.

I have tested your latest post and doesn’t seems to work.

I doesn’t show that it is not compatible but refuse to install.  If I hit the install button, it does nothing.  If I hit the uninstall button, it says that the plugins have been uninstalled.

[cid:image001.png@01D40D3E.0D968A10]

THX


[http://www.canadianmalartic.net/images/logo_mine.jpg]

Stéphan Doyon
Surintendant informatique et telecom | IT and Telecom. Superintendant
100, chemin du Lac Mourier, Malartic, Québec, J0Y 1Z0
Tél. : 819.757.2225 #2209 | Cell. : 819.856.5491 | Téléc. 819.757.2351
sdoyon@canadianmalartic.com<mailto:sdoyon@canadianmalartic.com> | www.canadianmalartic.com<http://www.canadianmalartic.com/>

[http://www.canadianmalartic.net/images/logo-ss-fr.jpg]

[http://www.canadianmalartic.net/images/6.jpg]
Message de confidentialité : Ce courriel (de même que les fichiers joints) est strictement réservé à l'usage de la personne ou de l'entité à qui il est adressé et peut contenir de l'information privilégiée et confidentielle. Toute divulgation, distribution ou copie de ce courriel est strictement prohibée. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser sur-le-champ, détruire toutes les copies et le supprimer de votre système informatique.
Confidentiality Notice: This e-mail transmission (and/or the attachments accompanying it) may contain legally privileged and confidential information, and is intended only for the use of the individual or entity named above. If you are not the intended recipient, you are hereby notified that any dissemination, disclosure, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please promptly notify the sender by reply e-mail and destroy the original message. Thank you.
De : Christian Bernard <notifications@github.com>
Envoyé : mardi, juin 26, 2018 10:30 AM
À : bacus99/Services <Services@noreply.github.com>
Cc : Stéphan Doyon <sdoyon@canadianmalartic.com>; Comment <comment@noreply.github.com>
Objet : Re: [bacus99/Services] glpi-9.2 is not yet supported (#11)


try this version
services.zip<https://github.com/bacus99/Services/files/2137547/services.zip>

**Comment by bacus99** [comment]
Now compatible with 9.2.4
